### ISSUE TITLE
SET storage_engine not valid on MySQL 5.7

### ISSUE THREAD

**Issue by marpada** [netzwirt/ansible-seafile#2]
Hi,

Great role! I had a problem on Ubuntu 16.04 though as the following syntax on seahub_settings.py.j2  is no longer valid with MySQL 5.7

` 'init_command': 'SET storage_engine=INNODB',`

valid syntax is:

` 'init_command': 'SET default_storage_engine=INNODB',`

Re: https://forum.seafile.de/t/solved-seahub-failure-after-mysql-5-7-upgrade/4680/5

**Comment by netzwirt** [comment]
Added to template

**Comment by marpada** [comment]
Thanks. The fix might break all other distros running MySQL < 5.7 though
